repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: validate-resume
        name: hackmyresume
        language: node
        entry: hackmyresume validate --assert resume.json
        args: []
        files: ''
        types: [json]
