repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: validate-resume
        name: hackmyresume
        language: node
        entry: hackmyresume
        # always_run: true
        args: ["validate --assert"]
        files: 'resume.json'
        types: [json]
